/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An attachment for an email message.
 * @export
 * @interface Attachment
 */
export interface Attachment {
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    'Content'?: string;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    'ContentID'?: string;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    'ContentType'?: string;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    'Name'?: string;
}

