/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BounceInfoResponse } from './bounce-info-response';

/**
 * 
 * @export
 * @interface BounceSearchResponse
 */
export interface BounceSearchResponse {
    /**
     * 
     * @type {Array<BounceInfoResponse>}
     * @memberof BounceSearchResponse
     */
    'Bounces'?: Array<BounceInfoResponse>;
    /**
     * 
     * @type {number}
     * @memberof BounceSearchResponse
     */
    'TotalCount'?: number;
}

