/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BounceDumpResponse
 */
export interface BounceDumpResponse {
    /**
     * Raw source of bounce. If no dump is available this will return an empty string.
     * @type {string}
     * @memberof BounceDumpResponse
     */
    'Body'?: string;
}

