/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BounceCountElement
 */
export interface BounceCountElement {
    /**
     * 
     * @type {number}
     * @memberof BounceCountElement
     */
    'Count'?: number;
    /**
     * 
     * @type {string}
     * @memberof BounceCountElement
     */
    'Name'?: string;
    /**
     * 
     * @type {string}
     * @memberof BounceCountElement
     */
    'Type'?: string;
}

