/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BounceInfoResponse } from './bounce-info-response';

/**
 * 
 * @export
 * @interface BounceActivationResponse
 */
export interface BounceActivationResponse {
    /**
     * 
     * @type {BounceInfoResponse}
     * @memberof BounceActivationResponse
     */
    'Bounce'?: BounceInfoResponse;
    /**
     * 
     * @type {string}
     * @memberof BounceActivationResponse
     */
    'Message'?: string;
}

