/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BounceInfoResponse
 */
export interface BounceInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof BounceInfoResponse
     */
    'BouncedAt'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BounceInfoResponse
     */
    'CanActivate'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BounceInfoResponse
     */
    'Content'?: string;
    /**
     * 
     * @type {string}
     * @memberof BounceInfoResponse
     */
    'Description'?: string;
    /**
     * 
     * @type {string}
     * @memberof BounceInfoResponse
     */
    'Details'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BounceInfoResponse
     */
    'DumpAvailable'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BounceInfoResponse
     */
    'Email'?: string;
    /**
     * 
     * @type {string}
     * @memberof BounceInfoResponse
     */
    'ID'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BounceInfoResponse
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BounceInfoResponse
     */
    'MessageID'?: string;
    /**
     * 
     * @type {string}
     * @memberof BounceInfoResponse
     */
    'Name'?: string;
    /**
     * 
     * @type {string}
     * @memberof BounceInfoResponse
     */
    'Subject'?: string;
    /**
     * 
     * @type {string}
     * @memberof BounceInfoResponse
     */
    'Tag'?: string;
    /**
     * 
     * @type {string}
     * @memberof BounceInfoResponse
     */
    'Type'?: string;
    /**
     * 
     * @type {number}
     * @memberof BounceInfoResponse
     */
    'TypeCode'?: number;
}

