/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The contents required for creating a new template.
 * @export
 * @interface CreateTemplateRequest
 */
export interface CreateTemplateRequest {
    /**
     * The optional string identifier for referring to this Template (numbers, letters, and \'.\', \'-\', \'_\' characters, starts with a letter).
     * @type {string}
     * @memberof CreateTemplateRequest
     */
    'Alias'?: string;
    /**
     * The HTML template definition for this Template.
     * @type {string}
     * @memberof CreateTemplateRequest
     */
    'HtmlBody'?: string;
    /**
     * The friendly display name for the template.
     * @type {string}
     * @memberof CreateTemplateRequest
     */
    'Name': string;
    /**
     * The Subject template definition for this Template.
     * @type {string}
     * @memberof CreateTemplateRequest
     */
    'Subject': string;
    /**
     * The Text template definition for this Template.
     * @type {string}
     * @memberof CreateTemplateRequest
     */
    'TextBody'?: string;
}

