/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BounceCountElement } from './bounce-count-element';

/**
 * 
 * @export
 * @interface DeliveryStatsResponse
 */
export interface DeliveryStatsResponse {
    /**
     * 
     * @type {Array<BounceCountElement>}
     * @memberof DeliveryStatsResponse
     */
    'Bounces'?: Array<BounceCountElement>;
    /**
     * 
     * @type {number}
     * @memberof DeliveryStatsResponse
     */
    'InactiveMails'?: number;
}

