/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EditServerConfigurationRequest
 */
export interface EditServerConfigurationRequest {
    /**
     * 
     * @type {string}
     * @memberof EditServerConfigurationRequest
     */
    'BounceHookUrl'?: string;
    /**
     * Webhook url allowing real-time notification when tracked links are clicked.
     * @type {string}
     * @memberof EditServerConfigurationRequest
     */
    'ClickHookUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditServerConfigurationRequest
     */
    'Color'?: EditServerConfigurationRequestColorEnum;
    /**
     * 
     * @type {string}
     * @memberof EditServerConfigurationRequest
     */
    'DeliveryHookUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditServerConfigurationRequest
     */
    'InboundDomain'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditServerConfigurationRequest
     */
    'InboundHookUrl'?: string;
    /**
     * 
     * @type {number}
     * @memberof EditServerConfigurationRequest
     */
    'InboundSpamThreshold'?: number;
    /**
     * 
     * @type {string}
     * @memberof EditServerConfigurationRequest
     */
    'Name'?: string;
    /**
     * 
     * @type {string}
     * @memberof EditServerConfigurationRequest
     */
    'OpenHookUrl'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EditServerConfigurationRequest
     */
    'PostFirstOpenOnly'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditServerConfigurationRequest
     */
    'RawEmailEnabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditServerConfigurationRequest
     */
    'SmtpApiActivated'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EditServerConfigurationRequest
     */
    'TrackLinks'?: EditServerConfigurationRequestTrackLinksEnum;
    /**
     * 
     * @type {boolean}
     * @memberof EditServerConfigurationRequest
     */
    'TrackOpens'?: boolean;
}

type EditServerConfigurationRequestColorEnum = 'purple' | 'blue' | 'turqoise' | 'green' | 'red' | 'yellow' | 'grey'
type EditServerConfigurationRequestTrackLinksEnum = 'None' | 'HtmlAndText' | 'HtmlOnly' | 'TextOnly'


