/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Attachment } from './attachment';
import { MessageHeader } from './message-header';

/**
 * 
 * @export
 * @interface EmailWithTemplateRequest
 */
export interface EmailWithTemplateRequest {
    /**
     * 
     * @type {Array<Attachment>}
     * @memberof EmailWithTemplateRequest
     */
    'Attachments'?: Array<Attachment>;
    /**
     * 
     * @type {string}
     * @memberof EmailWithTemplateRequest
     */
    'Bcc'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailWithTemplateRequest
     */
    'Cc'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailWithTemplateRequest
     */
    'From': string;
    /**
     * 
     * @type {Array<MessageHeader>}
     * @memberof EmailWithTemplateRequest
     */
    'Headers'?: Array<MessageHeader>;
    /**
     * 
     * @type {boolean}
     * @memberof EmailWithTemplateRequest
     */
    'InlineCss'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EmailWithTemplateRequest
     */
    'ReplyTo'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmailWithTemplateRequest
     */
    'Tag'?: string;
    /**
     * Required if \'TemplateId\' is not specified.
     * @type {string}
     * @memberof EmailWithTemplateRequest
     */
    'TemplateAlias': string;
    /**
     * Required if \'TemplateAlias\' is not specified.
     * @type {number}
     * @memberof EmailWithTemplateRequest
     */
    'TemplateId': number;
    /**
     * 
     * @type {object}
     * @memberof EmailWithTemplateRequest
     */
    'TemplateModel': object;
    /**
     * 
     * @type {string}
     * @memberof EmailWithTemplateRequest
     */
    'To': string;
    /**
     * Replace links in content to enable \"click tracking\" stats. Default is \'null\', which uses the server\'s LinkTracking setting\'.
     * @type {string}
     * @memberof EmailWithTemplateRequest
     */
    'TrackLinks'?: EmailWithTemplateRequestTrackLinksEnum;
    /**
     * Activate open tracking for this email.
     * @type {boolean}
     * @memberof EmailWithTemplateRequest
     */
    'TrackOpens'?: boolean;
}

type EmailWithTemplateRequestTrackLinksEnum = 'None' | 'HtmlAndText' | 'HtmlOnly' | 'TextOnly'


