/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ExtendedMessageClickEventInformationGeo
 */
export interface ExtendedMessageClickEventInformationGeo {
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformationGeo
     */
    'City'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformationGeo
     */
    'Coords'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformationGeo
     */
    'Country'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformationGeo
     */
    'CountryISOCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformationGeo
     */
    'IP'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformationGeo
     */
    'Region'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformationGeo
     */
    'RegionISOCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformationGeo
     */
    'Zip'?: string;
}

