/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExtendedMessageClickEventInformationClient } from './extended-message-click-event-information-client';
import { ExtendedMessageClickEventInformationGeo } from './extended-message-click-event-information-geo';
import { ExtendedMessageClickEventInformationOS } from './extended-message-click-event-information-os';

/**
 * 
 * @export
 * @interface ExtendedMessageClickEventInformation
 */
export interface ExtendedMessageClickEventInformation {
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformation
     */
    'ClickLocation'?: string;
    /**
     * 
     * @type {ExtendedMessageClickEventInformationClient}
     * @memberof ExtendedMessageClickEventInformation
     */
    'Client'?: ExtendedMessageClickEventInformationClient;
    /**
     * 
     * @type {ExtendedMessageClickEventInformationGeo}
     * @memberof ExtendedMessageClickEventInformation
     */
    'Geo'?: ExtendedMessageClickEventInformationGeo;
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformation
     */
    'MessageID'?: string;
    /**
     * 
     * @type {ExtendedMessageClickEventInformationOS}
     * @memberof ExtendedMessageClickEventInformation
     */
    'OS'?: ExtendedMessageClickEventInformationOS;
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformation
     */
    'OriginalLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformation
     */
    'Platform'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformation
     */
    'ReceivedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformation
     */
    'Recipient'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformation
     */
    'Tag'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedMessageClickEventInformation
     */
    'UserAgent'?: string;
}

