/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Attachment } from './attachment';
import { EmailNameAddressPair } from './email-name-address-pair';
import { InboundMessageDetailFromFull } from './inbound-message-detail-from-full';

/**
 * 
 * @export
 * @interface InboundMessageDetail
 */
export interface InboundMessageDetail {
    /**
     * 
     * @type {Array<Attachment>}
     * @memberof InboundMessageDetail
     */
    'Attachments'?: Array<Attachment>;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageDetail
     */
    'Cc'?: string;
    /**
     * 
     * @type {Array<EmailNameAddressPair>}
     * @memberof InboundMessageDetail
     */
    'CcFull'?: Array<EmailNameAddressPair>;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageDetail
     */
    'Date'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageDetail
     */
    'From'?: string;
    /**
     * 
     * @type {InboundMessageDetailFromFull}
     * @memberof InboundMessageDetail
     */
    'FromFull'?: InboundMessageDetailFromFull;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageDetail
     */
    'FromName'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageDetail
     */
    'MailboxHash'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageDetail
     */
    'MessageID'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageDetail
     */
    'OriginalRecipient'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageDetail
     */
    'ReplyTo'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageDetail
     */
    'Status'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageDetail
     */
    'Subject'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageDetail
     */
    'Tag'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageDetail
     */
    'To'?: string;
    /**
     * 
     * @type {Array<EmailNameAddressPair>}
     * @memberof InboundMessageDetail
     */
    'ToFull'?: Array<EmailNameAddressPair>;
}

