/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InboundMessageDetailFromFull
 */
export interface InboundMessageDetailFromFull {
    /**
     * 
     * @type {string}
     * @memberof InboundMessageDetailFromFull
     */
    'Email'?: string;
    /**
     * 
     * @type {string}
     * @memberof InboundMessageDetailFromFull
     */
    'Name'?: string;
}

