/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InboundMessageDetail } from './inbound-message-detail';

/**
 * 
 * @export
 * @interface InboundSearchResponse
 */
export interface InboundSearchResponse {
    /**
     * 
     * @type {Array<InboundMessageDetail>}
     * @memberof InboundSearchResponse
     */
    'InboundMessages'?: Array<InboundMessageDetail>;
    /**
     * 
     * @type {number}
     * @memberof InboundSearchResponse
     */
    'TotalCount'?: number;
}

