/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A single header for an email message.
 * @export
 * @interface MessageHeader
 */
export interface MessageHeader {
    /**
     * The header\'s name.
     * @type {string}
     * @memberof MessageHeader
     */
    'Name'?: string;
    /**
     * The header\'s value.
     * @type {string}
     * @memberof MessageHeader
     */
    'Value'?: string;
}

