/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MessageEventDetailsDetails
 */
export interface MessageEventDetailsDetails {
    /**
     * 
     * @type {string}
     * @memberof MessageEventDetailsDetails
     */
    'BounceID'?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageEventDetailsDetails
     */
    'DeliveryMessage'?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageEventDetailsDetails
     */
    'DestinationIP'?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageEventDetailsDetails
     */
    'DestinationServer'?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageEventDetailsDetails
     */
    'Summary'?: string;
}

