/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExtendedMessageClickEventInformation } from './extended-message-click-event-information';

/**
 * 
 * @export
 * @interface MessageClickSearchResponse
 */
export interface MessageClickSearchResponse {
    /**
     * 
     * @type {Array<ExtendedMessageClickEventInformation>}
     * @memberof MessageClickSearchResponse
     */
    'Clicks'?: Array<ExtendedMessageClickEventInformation>;
    /**
     * 
     * @type {number}
     * @memberof MessageClickSearchResponse
     */
    'TotalCount'?: number;
}

