/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Attachment } from './attachment';
import { EmailNameAddressPair } from './email-name-address-pair';

/**
 * 
 * @export
 * @interface OutboundMessageDetail
 */
export interface OutboundMessageDetail {
    /**
     * 
     * @type {Array<Attachment>}
     * @memberof OutboundMessageDetail
     */
    'Attachments'?: Array<Attachment>;
    /**
     * 
     * @type {Array<EmailNameAddressPair>}
     * @memberof OutboundMessageDetail
     */
    'Bcc'?: Array<EmailNameAddressPair>;
    /**
     * 
     * @type {Array<EmailNameAddressPair>}
     * @memberof OutboundMessageDetail
     */
    'Cc'?: Array<EmailNameAddressPair>;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetail
     */
    'From'?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetail
     */
    'MessageID'?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetail
     */
    'ReceivedAt'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OutboundMessageDetail
     */
    'Recipients'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetail
     */
    'Status'?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetail
     */
    'Subject'?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetail
     */
    'Tag'?: string;
    /**
     * 
     * @type {Array<EmailNameAddressPair>}
     * @memberof OutboundMessageDetail
     */
    'To'?: Array<EmailNameAddressPair>;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetail
     */
    'TrackLinks'?: OutboundMessageDetailTrackLinksEnum;
    /**
     * 
     * @type {boolean}
     * @memberof OutboundMessageDetail
     */
    'TrackOpens'?: boolean;
}

type OutboundMessageDetailTrackLinksEnum = 'None' | 'HtmlAndText' | 'HtmlOnly' | 'TextOnly'


