/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Attachment } from './attachment';
import { EmailNameAddressPair } from './email-name-address-pair';
import { MessageEventDetails } from './message-event-details';

/**
 * 
 * @export
 * @interface OutboundMessageDetailsResponse
 */
export interface OutboundMessageDetailsResponse {
    /**
     * 
     * @type {Array<Attachment>}
     * @memberof OutboundMessageDetailsResponse
     */
    'Attachments'?: Array<Attachment>;
    /**
     * 
     * @type {Array<EmailNameAddressPair>}
     * @memberof OutboundMessageDetailsResponse
     */
    'Bcc'?: Array<EmailNameAddressPair>;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetailsResponse
     */
    'Body'?: string;
    /**
     * 
     * @type {Array<EmailNameAddressPair>}
     * @memberof OutboundMessageDetailsResponse
     */
    'Cc'?: Array<EmailNameAddressPair>;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetailsResponse
     */
    'From'?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetailsResponse
     */
    'HtmlBody'?: string;
    /**
     * 
     * @type {Array<MessageEventDetails>}
     * @memberof OutboundMessageDetailsResponse
     */
    'MessageEvents'?: Array<MessageEventDetails>;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetailsResponse
     */
    'MessageID'?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetailsResponse
     */
    'ReceivedAt'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OutboundMessageDetailsResponse
     */
    'Recipients'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetailsResponse
     */
    'Status'?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetailsResponse
     */
    'Subject'?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetailsResponse
     */
    'Tag'?: string;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetailsResponse
     */
    'TextBody'?: string;
    /**
     * 
     * @type {Array<EmailNameAddressPair>}
     * @memberof OutboundMessageDetailsResponse
     */
    'To'?: Array<EmailNameAddressPair>;
    /**
     * 
     * @type {string}
     * @memberof OutboundMessageDetailsResponse
     */
    'TrackLinks'?: OutboundMessageDetailsResponseTrackLinksEnum;
    /**
     * 
     * @type {boolean}
     * @memberof OutboundMessageDetailsResponse
     */
    'TrackOpens'?: boolean;
}

type OutboundMessageDetailsResponseTrackLinksEnum = 'None' | 'HtmlAndText' | 'HtmlOnly' | 'TextOnly'


