/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OutboundMessageDetail } from './outbound-message-detail';

/**
 * 
 * @export
 * @interface OutboundSearchResponse
 */
export interface OutboundSearchResponse {
    /**
     * 
     * @type {Array<OutboundMessageDetail>}
     * @memberof OutboundSearchResponse
     */
    'Messages'?: Array<OutboundMessageDetail>;
    /**
     * 
     * @type {number}
     * @memberof OutboundSearchResponse
     */
    'TotalCount'?: number;
}

