/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Attachment } from './attachment';
import { MessageHeader } from './message-header';

/**
 * 
 * @export
 * @interface SendEmailRequest
 */
export interface SendEmailRequest {
    /**
     * 
     * @type {Array<Attachment>}
     * @memberof SendEmailRequest
     */
    'Attachments'?: Array<Attachment>;
    /**
     * Bcc recipient email address. Multiple addresses are comma seperated. Max 50.
     * @type {string}
     * @memberof SendEmailRequest
     */
    'Bcc'?: string;
    /**
     * Recipient email address. Multiple addresses are comma seperated. Max 50.
     * @type {string}
     * @memberof SendEmailRequest
     */
    'Cc'?: string;
    /**
     * The sender email address. Must have a registered and confirmed Sender Signature.
     * @type {string}
     * @memberof SendEmailRequest
     */
    'From'?: string;
    /**
     * 
     * @type {Array<MessageHeader>}
     * @memberof SendEmailRequest
     */
    'Headers'?: Array<MessageHeader>;
    /**
     * If no TextBody specified HTML email message
     * @type {string}
     * @memberof SendEmailRequest
     */
    'HtmlBody'?: string;
    /**
     * Reply To override email address. Defaults to the Reply To set in the sender signature.
     * @type {string}
     * @memberof SendEmailRequest
     */
    'ReplyTo'?: string;
    /**
     * Email Subject
     * @type {string}
     * @memberof SendEmailRequest
     */
    'Subject'?: string;
    /**
     * Email tag that allows you to categorize outgoing emails and get detailed statistics.
     * @type {string}
     * @memberof SendEmailRequest
     */
    'Tag'?: string;
    /**
     * If no HtmlBody specified Plain text email message
     * @type {string}
     * @memberof SendEmailRequest
     */
    'TextBody'?: string;
    /**
     * Recipient email address. Multiple addresses are comma seperated. Max 50.
     * @type {string}
     * @memberof SendEmailRequest
     */
    'To'?: string;
    /**
     * Replace links in content to enable \"click tracking\" stats. Default is \'null\', which uses the server\'s LinkTracking setting\'.
     * @type {string}
     * @memberof SendEmailRequest
     */
    'TrackLinks'?: SendEmailRequestTrackLinksEnum;
    /**
     * Activate open tracking for this email.
     * @type {boolean}
     * @memberof SendEmailRequest
     */
    'TrackOpens'?: boolean;
}

type SendEmailRequestTrackLinksEnum = 'None' | 'HtmlAndText' | 'HtmlOnly' | 'TextOnly'


