/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SentCountsResponseDaysInner } from './sent-counts-response-days-inner';

/**
 * The result of a get sent counts operation.
 * @export
 * @interface SentCountsResponse
 */
export interface SentCountsResponse {
    /**
     * 
     * @type {Array<SentCountsResponseDaysInner>}
     * @memberof SentCountsResponse
     */
    'Days'?: Array<SentCountsResponseDaysInner>;
    /**
     * 
     * @type {number}
     * @memberof SentCountsResponse
     */
    'Sent'?: number;
}

