/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SentCountsResponseDaysInner
 */
export interface SentCountsResponseDaysInner {
    /**
     * 
     * @type {string}
     * @memberof SentCountsResponseDaysInner
     */
    'Date'?: string;
    /**
     * 
     * @type {number}
     * @memberof SentCountsResponseDaysInner
     */
    'Sent'?: number;
}

