/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ServerConfigurationResponse
 */
export interface ServerConfigurationResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof ServerConfigurationResponse
     */
    'ApiTokens'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ServerConfigurationResponse
     */
    'BounceHookUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServerConfigurationResponse
     */
    'ClickHookUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServerConfigurationResponse
     */
    'Color'?: ServerConfigurationResponseColorEnum;
    /**
     * 
     * @type {string}
     * @memberof ServerConfigurationResponse
     */
    'DeliveryHookUrl'?: string;
    /**
     * 
     * @type {number}
     * @memberof ServerConfigurationResponse
     */
    'ID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ServerConfigurationResponse
     */
    'InboundAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServerConfigurationResponse
     */
    'InboundDomain'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServerConfigurationResponse
     */
    'InboundHash'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServerConfigurationResponse
     */
    'InboundHookUrl'?: string;
    /**
     * 
     * @type {number}
     * @memberof ServerConfigurationResponse
     */
    'InboundSpamThreshold'?: number;
    /**
     * 
     * @type {string}
     * @memberof ServerConfigurationResponse
     */
    'Name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServerConfigurationResponse
     */
    'OpenHookUrl'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ServerConfigurationResponse
     */
    'PostFirstOpenOnly'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ServerConfigurationResponse
     */
    'RawEmailEnabled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ServerConfigurationResponse
     */
    'ServerLink'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ServerConfigurationResponse
     */
    'SmtpApiActivated'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ServerConfigurationResponse
     */
    'TrackLinks'?: ServerConfigurationResponseTrackLinksEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ServerConfigurationResponse
     */
    'TrackOpens'?: boolean;
}

type ServerConfigurationResponseColorEnum = 'purple' | 'blue' | 'turqoise' | 'green' | 'red' | 'yellow' | 'grey'
type ServerConfigurationResponseTrackLinksEnum = 'None' | 'HtmlAndText' | 'HtmlOnly' | 'TextOnly'


