/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A Postmark API error.
 * @export
 * @interface StandardPostmarkResponse
 */
export interface StandardPostmarkResponse {
    /**
     * 
     * @type {number}
     * @memberof StandardPostmarkResponse
     */
    'ErrorCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof StandardPostmarkResponse
     */
    'Message'?: string;
}

