/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TemplateRecordResponse
 */
export interface TemplateRecordResponse {
    /**
     * True if this template is currently available for use.
     * @type {boolean}
     * @memberof TemplateRecordResponse
     */
    'Active'?: boolean;
    /**
     * The user-supplied alias for this template.
     * @type {string}
     * @memberof TemplateRecordResponse
     */
    'Alias'?: string;
    /**
     * The display name for this template.
     * @type {string}
     * @memberof TemplateRecordResponse
     */
    'Name'?: string;
    /**
     * The associated ID for this template.
     * @type {number}
     * @memberof TemplateRecordResponse
     */
    'TemplateId'?: number;
}

