/*
Postmark API

Postmark makes sending and receiving email
incredibly easy.


The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TemplateRecordResponse } from './template-record-response';

/**
 * 
 * @export
 * @interface TemplateListingResponse
 */
export interface TemplateListingResponse {
    /**
     * Basic information for each Template returned from the query.
     * @type {Array<TemplateRecordResponse>}
     * @memberof TemplateListingResponse
     */
    'Templates API'?: Array<TemplateRecordResponse>;
    /**
     * The total number of Templates API associated with this server.
     * @type {number}
     * @memberof TemplateListingResponse
     */
    'TotalCount'?: number;
}

